# Content

1. Getting Started. 1a. Tensors. 1b. Operations

2. NumPy Bridge2a. Converting a Torch Tensor to a NumPy Array
2b. Converting NumPy Array to Torch Tensor

3. CUDA Tensors

In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

1.Getting Started
---------------

# 1a. Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[-20881553239852680642931632111616.0000,
                                         0.0000,
                                        -0.0000],
        [                                0.0000,
                                         0.0000,
                                         0.0000],
        [                                0.0000,
                                         0.0000,
                                         0.0000],
        [                                0.0000,
                                         0.0000,
                                         0.0000],
        [                                0.0000,
                                         0.0000,
                                        -0.0000]])


Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8644, 0.4042, 0.2621],
        [0.7648, 0.6773, 0.1395],
        [0.0347, 0.2777, 0.4679],
        [0.9630, 0.7768, 0.5524],
        [0.7270, 0.8400, 0.4062]])


Construct a matrix filled zeros and of dtype long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4998, -0.5800,  0.6384],
        [-1.2790,  0.4482, -0.0200],
        [-1.2390, -0.2637, -1.3047],
        [ 0.5016,  0.3716,  1.3442],
        [-0.4340, -0.9080,  1.6843]])


Get its size:



In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

# 1b. Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5107,  0.1423,  1.2637],
        [-0.6951,  0.8119,  0.4561],
        [-0.5973, -0.1464, -0.5805],
        [ 1.2909,  0.5958,  2.1270],
        [ 0.5191, -0.8339,  2.2522]])


Addition: syntax 2



In [11]:
print(torch.add(x, y))

tensor([[ 0.5107,  0.1423,  1.2637],
        [-0.6951,  0.8119,  0.4561],
        [-0.5973, -0.1464, -0.5805],
        [ 1.2909,  0.5958,  2.1270],
        [ 0.5191, -0.8339,  2.2522]])


Addition: providing an output tensor as argument



In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5107,  0.1423,  1.2637],
        [-0.6951,  0.8119,  0.4561],
        [-0.5973, -0.1464, -0.5805],
        [ 1.2909,  0.5958,  2.1270],
        [ 0.5191, -0.8339,  2.2522]])


Addition: in-place



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5107,  0.1423,  1.2637],
        [-0.6951,  0.8119,  0.4561],
        [-0.5973, -0.1464, -0.5805],
        [ 1.2909,  0.5958,  2.1270],
        [ 0.5191, -0.8339,  2.2522]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [16]:
print(x[:, 1])

tensor([-0.5800,  0.4482, -0.2637,  0.3716, -0.9080])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0789])
-1.0788556337356567


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

# 2. NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

# 2a. Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# 2b. Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

# 3. CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [23]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.0789], device='cuda:0')
tensor([-0.0789], dtype=torch.float64)
